// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8JroV-sm3ypbVc5rosWL3AcZKXyv2D8',
    appId: '1:629259555870:web:e6fcb120e7a64b08af4a0f',
    messagingSenderId: '629259555870',
    projectId: 'note-app-1234',
    authDomain: 'note-app-1234.firebaseapp.com',
    storageBucket: 'note-app-1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ZT45U5AORTsvUf8lHoaWLm4vag4Maog',
    appId: '1:629259555870:android:0204586b663e8132af4a0f',
    messagingSenderId: '629259555870',
    projectId: 'note-app-1234',
    storageBucket: 'note-app-1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVY89JTK3ZOUdxqnkGXd2E-9a7mOr5vao',
    appId: '1:629259555870:ios:3fe0819a09a109fbaf4a0f',
    messagingSenderId: '629259555870',
    projectId: 'note-app-1234',
    storageBucket: 'note-app-1234.appspot.com',
    iosBundleId: 'com.prac.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVY89JTK3ZOUdxqnkGXd2E-9a7mOr5vao',
    appId: '1:629259555870:ios:3fe0819a09a109fbaf4a0f',
    messagingSenderId: '629259555870',
    projectId: 'note-app-1234',
    storageBucket: 'note-app-1234.appspot.com',
    iosBundleId: 'com.prac.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw8JroV-sm3ypbVc5rosWL3AcZKXyv2D8',
    appId: '1:629259555870:web:e23e13b9fa76f828af4a0f',
    messagingSenderId: '629259555870',
    projectId: 'note-app-1234',
    authDomain: 'note-app-1234.firebaseapp.com',
    storageBucket: 'note-app-1234.appspot.com',
  );
}
